# Generated by Django 5.2.8 on 2025-12-15 16:29

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('is_ready', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=core.models.generate_code, max_length=10, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='grid_tdoa', max_length=50)),
                ('estimated_x', models.FloatField(blank=True, null=True)),
                ('estimated_y', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_mics', models.PositiveIntegerField(default=0)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.recordinground')),
            ],
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=core.models.audio_segment_upload_to)),
                ('segment_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_url', models.CharField(blank=True, max_length=500, null=True)),
                ('microphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='core.microphone')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.recordinground')),
            ],
        ),
        migrations.AddField(
            model_name='recordinground',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.session'),
        ),
        migrations.AddField(
            model_name='microphone',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microphone_data', to='core.session'),
        ),
    ]
