# Generated by Django 5.2.8 on 2025-11-07 21:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(default=core.models.generate_code, max_length=10, unique=True),
        ),
    ]
