# Generated by Django 5.2.8 on 2025-12-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiosegment_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='cloud_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
